### PR TITLE
Nits and formats

### PR DESCRIPTION
**Pull request by otherview**
Initial Pull Request for a structure change.

Submitting this for initial review of the structure, no point pursuing more changes if the structure change is not good to proceed.

- [X] The root folder is now the projecto for obscuro in golang 
- [X] Simulation is now a subfolder of the "obscurogo"
- [ ] Simulation libraries will be decoupled from obscurogo 
- [ ] obscurogo libraries will be defined outside of the simulation
- [X] Removed `.idea` and added IDE folders to the gitignore
- [X] Added `.golangci.yml` (Although there's a bug to be addressed when running `golangci-lint run ./...`)

### CODE REVIEW

**Comment by tudor-malene** [comment]
Thanks Pedro. This is a good initiative. The project definitely needs a better structure.

What about?
( inspired by https://github.com/ethereum-optimism/optimism )

root
| - contract: where the L1 contracts will go
|
| - go: all the backend go code 
|    | - obscuro-node
|
| - integration-tests: This is where the simulation & friends will go
      | - ethereum-mock
      | - wallet-mock: not sure this even makes sense
      | - simulation:

**Comment by otherview** [comment]
That makes sense 👍 

We'll probably change this further in the future, for sure it's not the last iteration.

I'll change the structure to match the suggestion.
```
root
| - contract: where the L1 contracts will go ( Won't add this as there's no contract yet)
|
| - go: all the backend go code
  | - obscuro-node
|
| - integration-tests: This is where the simulation & friends will go
  |
  | - ethereum-mock
  | - wallet-mock: not sure this even makes sense
  | - simulation:
```

**Comment by paulwizviz** [comment]
The Go convention is to have this structure if you plan to create multiple executables.

root
  |
  | - cmd
        | - simulation
              | - main.go
       |  - node
             | - main.go
  |
  | - <exportable module as per folder name> or pkg
                                                                                   | - <exportable module as per folder name>

**Comment by otherview** [comment]
> The Go convention is to have this structure if you plan to create multiple executables.
> 
> /cmd/ /cmd/simulation/main.go -- to create simulation.exe /cmd/node/main.go. -- to create node.exe /(exportable module as per folder name) / internal --- keep stuff not exportable
> 
> alternatively /pkg/(exportable module as per folder name)

You're right. I created the `cmd/` in the simulation folder to start addressing this.

**Pull request merged**
